### ISSUE TITLE
Fix Callout size(In Hight)

### ISSUE THREAD

**Issue by 0xDTC** [golam71/obsidian-hackthebox#2]
**Appearance looking like it right now**

![image](https://github.com/user-attachments/assets/4758718b-ef30-4a34-86a3-2fec7db60d32)

![image](https://github.com/user-attachments/assets/468913cc-a426-48ae-9b85-38ec0fb9a69f)

**Make It look bit minimalist in appearance**

![image](https://github.com/user-attachments/assets/d5a8e55c-264b-40f9-abed-0bce2636aff7)

![image](https://github.com/user-attachments/assets/19571d59-1f0c-4840-83c3-819517a11d93)

**Comment by golam71** [comment]
hello, thanks for raising this issue 
does this look ok?

![image](https://github.com/user-attachments/assets/8a84ac16-5805-433f-a9e0-99b4854c42e9)

**Comment by golam71** [comment]
fixed in [v2](https://github.com/golam71/obsidian-hackthebox/releases/tag/2.0.3)
you can now update the theme

**Comment by 0xDTC** [comment]
Great work
